apiVersion: apps/v1
kind: Deployment
metadata:
  name: flo-app-deployment
  labels:
    app: flo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flo-app
  template:
    metadata:
      labels:
        app: flo-app
    spec:
      containers:
      - name: flo-app
        image: 752359169410.dkr.ecr.us-east-1.amazonaws.com/flo-demo-docker-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: tcp
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flo-app
spec:
  selector:
    app: flo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
